### ISSUE TITLE
error in run_scenicplus

### ISSUE THREAD

**Issue by rdf1993** [aertslab/scenicplus#188]
from scenicplus.wrappers.run_scenicplus import run_scenicplus
try:
    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['ACC_celltype'],
        species = 'hsapiens',
        assembly = 'hg38',
        tf_file = '/mnt/volume3/rdf/00_biosoft/pycisTopic/TFdb/human_tfs_v_1.01.txt',
        save_path = os.path.join(work_dir, 'scenicplus'),
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = True,
        path_bedToBigBed = '/mnt/volume3/rdf/00_biosoft/scenicplus/',
        n_cpu = 12,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill'))
except Exception as e:
    #in case of failure, still save the object
    dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)
    raise(e)

2023-07-30 23:08:58,179 SCENIC+_wrapper INFO     Making eGRNs AUC UMAP
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "<stdin>", line 2, in <module>
  File "/mnt/volume3/rdf/00_biosoft/scenicplus/src/scenicplus/wrappers/run_scenicplus.py", line 290, in run_scenicplus
    run_eRegulons_umap(scplus_obj,
  File "/mnt/volume3/rdf/00_biosoft/scenicplus/src/scenicplus/dimensionality_reduction.py", line 294, in run_eRegulons_umap
    embedding = reducer.fit_transform(data_mat)
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 2772, in fit_transform
    self.fit(X, y)
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 2516, in fit
    ) = nearest_neighbors(
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 328, in nearest_neighbors
    knn_search_index = NNDescent(
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 921, in __init__
    self._neighbor_graph = nn_descent(
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'print': Cannot determine Numba type of <class 'function'>

File "../../../../../../home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 252:
def nn_descent_internal_low_memory_parallel(
    <source elided>
        if verbose:
            print("\t", n + 1, " / ", n_iters)
            ^

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7f74cccdf9d0>))
During: typing of call at /home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7f74cccdf9d0>))
During: typing of call at /home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)

File "../../../../../../home/ruandf/anaconda3/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 358:
def nn_descent(
    <source elided>
    if low_memory:
        nn_descent_internal_low_memory_parallel(
        ^

Python 3.8.17

**Comment by angeyang123** [comment]
Hi @rdf1993, I'm running into the same issue. Were you able to solve it and do you mind sharing how you did it? Thanks!

**Comment by massonix** [comment]
I have the same issue! Any updates on it?

**Comment by simozhou** [comment]
I also encountered the same issue! Has anyone found a way around it?

**Comment by SeppeDeWinter** [comment]
Hi @simozhou 

It's related to the numba version, which version do you have?

Best,

Seppe

**Comment by simozhou** [comment]
Hi @SeppeDeWinter,

Thank you for getting back to me so quickly!

```
>>> numba.__version__
'0.58.0'
```

I installed everything via conda last week and worked well without too many troubles

**Comment by SeppeDeWinter** [comment]
Hi @simozhou 

See: https://github.com/aertslab/scenicplus/issues/203

Best,

seppe
