### ISSUE TITLE
Linux installation Error

### ISSUE THREAD

**Issue by GeneVector5** [aertslab/scenicplus#193]
I ran `pip install -e .` based on the tutorial and at the very end of the installation, I got this red text error message that I am having a hard time understanding. Does anyone know why this error is happening and how to resolve it?

```
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpuu4a31nk get_requires_for_build_wheel /tmp/tmp_qyf3mvn
       cwd: /tmp/pip-install-0f7xkt3r/pysam
  Complete output (162 lines):
  # pysam: cython is available - using cythonize if necessary
  # pysam: htslib mode is shared
  # pysam: HTSLIB_CONFIGURE_OPTIONS=None
  # pysam: (sysconfig) CC=x86_64-linux-gnu-gcc -pthread
  # pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -fPIC
  # pysam: (sysconfig) LDFLAGS=-Wl,-Bsymbolic-functions  -Wl,-z,relro -g -fwrapv -O2
  checking for gcc... x86_64-linux-gnu-gcc -pthread
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether x86_64-linux-gnu-gcc -pthread accepts -g... yes
  checking for x86_64-linux-gnu-gcc -pthread option to accept ISO C89... none needed
  checking for ranlib... ranlib
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for C compiler warning flags... unknown
  configure: Default CFLAGS_ARM/X86: -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -fPIC
  checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... yes
  checking whether C compiler accepts -mavx2... yes
  checking whether C compiler accepts -mavx512f... yes
  checking whether C compiler supports ARM Neon... no
  checking for pkg-config... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking shared library type for unknown-Linux... plain .so
  checking whether the linker supports versioned symbols... no
  checking whether the compiler accepts -fvisibility=hidden... yes
  checking how to run the C preprocessor... x86_64-linux-gnu-gcc -pthread -E
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for stdlib.h... (cached) yes
  checking for unistd.h... (cached) yes
  checking for sys/param.h... yes
  checking for getpagesize... yes
  checking for working mmap... yes
  checking for gmtime_r... yes
  checking for fsync... yes
  checking for drand48... yes
  checking for srand48_deterministic... no
  checking whether fdatasync is declared... yes
  checking for fdatasync... yes
  checking for library containing log... -lm
  checking for zlib.h... yes
  checking for inflate in -lz... yes
  checking for library containing recv... none required
  checking for bzlib.h... yes
  checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
  checking for lzma.h... no
  checking for lzma_easy_buffer_encode in -llzma... no
  configure: error: liblzma development files not found
  
  The CRAM format may use LZMA2 compression, which is implemented in HTSlib
  by using compression routines from liblzma <http://tukaani.org/xz/>.
  
  Building HTSlib requires liblzma development files to be installed on the
  build machine; you may need to ensure a package such as liblzma-dev (on Debian
  or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
  xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
  
  Either configure with --disable-lzma (which will make some CRAM files
  produced elsewhere unreadable) or resolve this error to build HTSlib.
  checking for gcc... x86_64-linux-gnu-gcc -pthread
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether x86_64-linux-gnu-gcc -pthread accepts -g... yes
  checking for x86_64-linux-gnu-gcc -pthread option to accept ISO C89... none needed
  checking for ranlib... ranlib
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for C compiler warning flags... unknown
  configure: Default CFLAGS_ARM/X86: -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g   -fstack-protector-strong -Wformat -Werror=format-security  -g -fwrapv -O2    -fPIC
  checking whether C compiler accepts -mssse3 -mpopcnt -msse4.1... yes
  checking whether C compiler accepts -mavx2... yes
  checking whether C compiler accepts -mavx512f... yes
  checking whether C compiler supports ARM Neon... no
  checking for pkg-config... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking shared library type for unknown-Linux... plain .so
  checking whether the linker supports versioned symbols... no
  checking whether the compiler accepts -fvisibility=hidden... yes
  checking how to run the C preprocessor... x86_64-linux-gnu-gcc -pthread -E
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for stdlib.h... (cached) yes
  checking for unistd.h... (cached) yes
  checking for sys/param.h... yes
  checking for getpagesize... yes
  checking for working mmap... yes
  checking for gmtime_r... yes
  checking for fsync... yes
  checking for drand48... yes
  checking for srand48_deterministic... no
  checking whether fdatasync is declared... yes
  checking for fdatasync... yes
  checking for library containing log... -lm
  checking for zlib.h... yes
  checking for inflate in -lz... yes
  checking for library containing recv... none required
  checking for bzlib.h... yes
  checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
  checking for lzma.h... no
  checking for lzma_easy_buffer_encode in -llzma... no
  configure: error: liblzma development files not found
  
  The CRAM format may use LZMA2 compression, which is implemented in HTSlib
  by using compression routines from liblzma <http://tukaani.org/xz/>.
  
  Building HTSlib requires liblzma development files to be installed on the
  build machine; you may need to ensure a package such as liblzma-dev (on Debian
  or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
  xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
  
  Either configure with --disable-lzma (which will make some CRAM files
  produced elsewhere unreadable) or resolve this error to build HTSlib.
  config.mk:2: *** Resolve configure error first.  Stop.
  # pysam: htslib configure options: None
  Traceback (most recent call last):
    File "/tmp/tmpuu4a31nk", line 280, in <module>
      main()
    File "/tmp/tmpuu4a31nk", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpuu4a31nk", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-f_dhcvaf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-f_dhcvaf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-f_dhcvaf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-f_dhcvaf/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 383, in <module>
    File "<string>", line 79, in run_make_print_config
    File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpuu4a31nk get_requires_for_build_wheel /tmp/tmp_qyf3mvn Check the logs for full command output.
```

**Comment by SeppeDeWinter** [comment]
@GeneVector5 

Could you show the entire output of the command please?

Best,

Seppe

**Comment by crossworlds423** [comment]
Hi Seppe, I attached a textfile showing the entire command outputwhen trying to install it again
[entire_ouput.txt](https://github.com/aertslab/scenicplus/files/12389994/entire_ouput.txt)

**Comment by strawberry098** [comment]
I'm using python 3.8.15 in Jupyter notebook, and upon executing `!pip3 install .` , I get the following error:

`Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/setuptools_scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897) -- Some packages may not be found!
    Download error on https://pypi.org/simple/setuptools-scm/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897) -- Some packages may not be found!
    No local packages or working download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-689h3nko-build/setup.py", line 48, in <module>
        "Operating System :: OS Independent",
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-689h3nko-build/`

**Comment by strawberry098** [comment]
Hi @SeppeDeWinter 

I realized the install was calling an older version of python (e.g. 3.6), resulting in the above error.  When I tried the same code, adding the path of the updated python version, the download started normally.

However, the installation stalls for >1 hr (without going to the next line of code) after:
`Successfully built scenicplus loomxpy pyscenic pycistarget pycisTopic
Installing collected packages: virtualenv, openpyxl, docutils, dill, defusedxml, cytoolz, cython, cycler, contourpy, colorlog, colorama, cloudpickle, click, charset-normalizer, cffi, certifi, cachetools, blosc2, blessed, bleach, bidict, beautifulsoup4, Babel, attrs, async-timeout, array-api-compat, annotated-types, alabaster, aiosignal, accessible-pygments, tables, statistics, scikit-learn, scikit-image, rich, requests, referencing, python-Levenshtein, python-igraph, pydantic, progressbar2, pandas, multiprocessing_on_dill, matplotlib, MACS2, loompy, leidenalg, gpustat, google-auth, gevent, gensim, easydev, dataclasses-json, dask, cryptography, cattrs, bs4, aiohttp, tspex, tmtoolkit, statsmodels, sphinx, seaborn, rich-argparse, requests-cache, pyrle, pyranges, pyopenssl, pynndescent, pygam, mizani, jsonschema-specifications, harmonypy, grequests, google-api-core, geosketch, distributed, ctxcore, bokeh, anndata, aiohttp-cors, adjustText, umap-learn, sphinxcontrib-jquery, scatac-fragment-tools, scanorama, pyvis, pydata-sphinx-theme, pybiomart, plotnine, opencensus, numpydoc, mudata, jsonschema, ipywidgets, bioservices, sphinx_rtd_theme, sphinx_book_theme, scrublet, scanpy, ray, nbformat, ipympl, gseapy, bbknn, nbclient, arboreto, pyscenic, papermill, nbconvert, nbsphinx, loomxpy, nbsphinx_link, pycisTopic, pycistarget, scenicplus`

Is this normal (e.g. just takes some time) or not?

Thanks.

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

1 hour is a very long time ... are you using conda by any chance?

All the best.

Seppe

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

I'm sorry, but I'm not sure why it is taking so long for you to install... 
Are you trying to install the package on your local machine or on a cluster?

All the best,

Seppe

**Comment by strawberry098** [comment]
Hi @SeppeDeWinter 

I'm installing the package onto a server.

I decided to give conda a try and installed miniconda3.  However, upon `conda activate`, I get this error:
`CondaError: Run 'conda init' before 'conda activate'`

Despite I have ran `conda init` already and restart the shell.

The beginning of the command line now says `base`.  It should say `scenicplus` after conda activation, is that correct?

Thank you

**Comment by kakaisi** [comment]
Hi @SeppeDeWinter 
I have a problem when installing the scenicplus package, pycistopic, just this one, the problem is described as follows, can you help me solve it?


(scenicplus) [fang@localhost ~]$ cd scenicplus
(scenicplus) [fang@localhost scenicplus]$ pip install -e .
Obtaining file:///home/fang/scenicplus
  Preparing metadata (setup.py) ... done
Collecting pycisTopic@ git+https://github.com/aertslab/pycisTopic@master (from scenicplus==1.0.1.dev6+ge5ba6fc.d20240318)
  Cloning https://github.com/aertslab/pycisTopic (to revision master) to /tmp/pip-install-pdnam6rz/pycistopic_5076824fab544b069995e0a602d7abaa
  Running command git clone --filter=blob:none --quiet https://github.com/aertslab/pycisTopic /tmp/pip-install-pdnam6rz/pycistopic_5076824fab544b069995e0a602d7abaa
  fatal: unable to access 'https://github.com/aertslab/pycisTopic/': Failed to connect to github.com port 443 after 127246 ms: Couldn't connect to server
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/aertslab/pycisTopic /tmp/pip-install-pdnam6rz/pycistopic_5076824fab544b069995e0a602d7abaa did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/aertslab/pycisTopic /tmp/pip-install-pdnam6rz/pycistopic_5076824fab544b069995e0a602d7abaa did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(scenicplus) [fang@localhost scenicplus]$ python
Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:21:28) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scenicplus
>>> scenicplus.__version__
'1.0.1.dev6+ge5ba6fc.d20240314'
>>> pycistopic.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pycistopic' is not defined
>>>

**Comment by strawberry098** [comment]
Hi @SeppeDeWinter

I was able to activate the conda environment. At the last step `pip install -e `. I'm getting a similar error as before of `python setup.py egg_info did not run successfully` when I did the regular installation (without conda).

Here's the error message:

Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [56 lines of output]
WARNING: Cannot look at git URL git+https://github.com/aertslab/pycisTopic@master#egg=pycisTopic because it does not support lookup as web pages.
WARNING: Cannot look at git URL git+https://github.com/aertslab/pycistarget@master#egg=pycistarget because it does not support lookup as web pages.
WARNING: Cannot look at git URL git+https://github.com/aertslab/pySCENIC@master#egg=pyscenic because it does not support lookup as web pages.
WARNING: Cannot look at git URL git+https://github.com/aertslab/LoomXpy@main#egg=loomxpy because it does not support lookup as web pages.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /simple/setuptools-scm/
ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
ERROR: No matching distribution found for setuptools_scm
/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/init.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)
  Traceback (most recent call last):
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
      subprocess.check_call(cmd)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/jtse02/miniconda3/envs/scenicplus/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4p04y3lj', '--quiet', '--find-links', 'git+https://github.com/aertslab/pycisTopic@master#egg=pycisTopic', '--find-links', 'git+https://github.com/aertslab/pycistarget@master#egg=pycistarget', '--find-links', 'git+https://github.com/aertslab/pySCENIC@master#egg=pyscenic', '--find-links', 'git+https://github.com/aertslab/LoomXpy@main#egg=loomxpy', 'setuptools_scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/jtse02/scenicplus/setup.py", line 31, in <module>
      setuptools.setup(
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/__init__.py", line 102, in setup
      _install_setup_requires(attrs)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
      _fetch_build_eggs(dist)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
      dist.fetch_build_eggs(dist.setup_requires)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/dist.py", line 662, in fetch_build_eggs
      return _fetch_build_eggs(self, requires)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
      dist = self._resolve_dist(
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
      dist = best[req.key] = env.best_match(
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1135, in best_match
      return self.obtain(req, installer)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1147, in obtain
      return installer(requirement)
    File "/home/jtse02/miniconda3/envs/scenicplus/lib/python3.8/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/home/jtse02/miniconda3/envs/scenicplus/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4p04y3lj', '--quiet', '--find-links', 'git+https://github.com/aertslab/pycisTopic@master#egg=pycisTopic', '--find-links', 'git+https://github.com/aertslab/pycistarget@master#egg=pycistarget', '--find-links', 'git+https://github.com/aertslab/pySCENIC@master#egg=pyscenic', '--find-links', 'git+https://github.com/aertslab/LoomXpy@main#egg=loomxpy', 'setuptools_scm']' returned non-zero exit status 1.
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) - skipping

Thank you

**Comment by strawberry098** [comment]
I tried to install the development version of SCENIC+, but encountered an error 30 minutes into the installation:

  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

Like the error suggests, you need to have cargo installed (this is the Rust package manager).
See https://rustup.rs/ for more info.

All the best,

Seppe

**Comment by strawberry098** [comment]
@SeppeDeWinter Thanks for your reply.

I already installed rustup and cargo into the scenicplus folder, but this error persists.  I wonder if the path is correct?

![image](https://github.com/aertslab/scenicplus/assets/134091570/0d3d0d36-9631-4bcf-9f58-907f7e82d44c)

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

How did you install rust?

All the best,
Seppe

**Comment by strawberry098** [comment]
@SeppeDeWinter As recommended on https://rustup.rs/

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

Are you able to run?

```bash

cargo --version

```

Seppe

**Comment by strawberry098** [comment]
@SeppeDeWinter 

This is what I got: 

`$path/scenicplus/.cargo/bin/cargo --version`
`error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.`

**Comment by strawberry098** [comment]
@SeppeDeWinter 

How do I ensure the right cargo (path) is installed during scenicplus installation?

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

Did you run?

```bash

rustup default stable

```

Best,

Seppe

**Comment by strawberry098** [comment]
I ran `rustup default stable` and was able to retrieve the version number of cargo.

Then, I resumed `pip install .` of the development scenicplus and get the following error at the pycistarget stage:

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting loomxpy@ git+https://github.com/aertslab/LoomXpy@main (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/LoomXpy (to revision main) to /tmp/pip-install-9ipa6tf_/loomxpy_5a1424fde4ff4379973c0ed327ee5ec1
  Running command git clone --quiet https://github.com/aertslab/LoomXpy /tmp/pip-install-9ipa6tf_/loomxpy_5a1424fde4ff4379973c0ed327ee5ec1
  Resolved https://github.com/aertslab/LoomXpy to commit 61995ff10940968eac2cee8fe48300ab477a15d0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pycistarget@ git+https://github.com/aertslab/pycistarget@development (from scenicplus==1.0a1)
  Cloning https://github.com/aertslab/pycistarget (to revision development) to /tmp/pip-install-9ipa6tf_/pycistarget_ebded4a0ffcf4d36a53eddc8b312d183
  Running command git clone --quiet https://github.com/aertslab/pycistarget /tmp/pip-install-9ipa6tf_/pycistarget_ebded4a0ffcf4d36a53eddc8b312d183
  WARNING: Did not find branch or tag 'development', assuming revision or ref.
  Running command git checkout -q development
  error: pathspec 'development' did not match any file(s) known to git.
  error: subprocess-exited-with-error

  × git checkout -q development did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q development did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.

**Comment by SeppeDeWinter** [comment]
Hi @strawberry098 

The development branch of SCENIC+ has been renamed to "main". I would recommend to reclone the repository or rename te branch locally.

```bash

git branch -m development main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

```

Best,

Seppe
