### ISSUE TITLE
Error in nn_descent_internal_low_memory_parallel associated with numba

### ISSUE THREAD

**Issue by angeyang123** [aertslab/scenicplus#203]
Hi, this is related to #188 which was closed without a solution. I was using the 10k PBMC multiome dataset from 10x Genomics. I got the same error while running the 'run_scenicplus' step. Your help is highly appreciated! Thank you!

The code I used was:
```python
from scenicplus.wrappers.run_scenicplus import run_scenicplus
try:
    run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['GEX_celltype'],
        species = 'hsapiens',
        assembly = 'hg38',
        tf_file = '/home/jupyter-ayang/notebooks/scenic_plus/TF_names_v_1.01.txt',
        save_path = os.path.join(work_dir, 'scenicplus'),
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,     
        export_to_UCSC_file = True,
        path_bedToBigBed = '/home/jupyter-ayang/notebooks/scenic_plus',
        n_cpu = 20,
        _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
        _system_config={"local_fs_capacity_threshold": 0.99})
except Exception as e:
    #in case of failure, still save the object
    dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)
    raise(e)
```

The error I got during the 'Making eGRNs AUC UMAP' step was:
```python
TypingError                               Traceback (most recent call last)
Cell In[10], line 24
     21 except Exception as e:
     22     #in case of failure, still save the object
     23     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)
---> 24     raise(e)

Cell In[10], line 3
      1 from scenicplus.wrappers.run_scenicplus import run_scenicplus
      2 try:
----> 3     run_scenicplus(
      4         scplus_obj = scplus_obj,
      5         variable = ['GEX_celltype'],
      6         species = 'hsapiens',
      7         assembly = 'hg38',
      8         tf_file = '/home/jupyter-ayang/notebooks/scenic_plus/TF_names_v_1.01.txt',
      9         save_path = os.path.join(work_dir, 'scenicplus'),
     10         biomart_host = biomart_host,
     11         upstream = [1000, 150000],
     12         downstream = [1000, 150000],
     13         calculate_TF_eGRN_correlation = True,
     14         calculate_DEGs_DARs = True,
     15         export_to_loom_file = True,     
     16         export_to_UCSC_file = True,
     17         path_bedToBigBed = '/home/jupyter-ayang/notebooks/scenic_plus',
     18         n_cpu = 20,
     19         _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
     20         _system_config={"local_fs_capacity_threshold": 0.99})
     21 except Exception as e:
     22     #in case of failure, still save the object
     23     dill.dump(scplus_obj, open(os.path.join(work_dir, 'scenicplus/scplus_obj.pkl'), 'wb'), protocol=-1)

File ~/notebooks/scenic_plus/scenicplus/src/scenicplus/wrappers/run_scenicplus.py:290, in run_scenicplus(scplus_obj, variable, species, assembly, tf_file, save_path, biomart_host, upstream, downstream, region_ranking, gene_ranking, simplified_eGRN, calculate_TF_eGRN_correlation, calculate_DEGs_DARs, export_to_loom_file, export_to_UCSC_file, tree_structure, path_bedToBigBed, n_cpu, _temp_dir, save_partial, **kwargs)
    288 if 'eRegulons_UMAP' not in scplus_obj.dr_cell.keys():
    289     log.info('Making eGRNs AUC UMAP')
--> 290     run_eRegulons_umap(scplus_obj,
    291                scale=True, signature_keys=['Gene_based', 'Region_based'])
    292 if 'eRegulons_tSNE' not in scplus_obj.dr_cell.keys():
    293     log.info('Making eGRNs AUC tSNE')

File ~/notebooks/scenic_plus/scenicplus/src/scenicplus/dimensionality_reduction.py:294, in run_eRegulons_umap(scplus_obj, scale, auc_key, signature_keys, reduction_name, random_state, selected_regulons, selected_cells, **kwargs)
    291 data_mat = data_mat.T.fillna(0)
    293 reducer = umap.UMAP(random_state=random_state, **kwargs)
--> 294 embedding = reducer.fit_transform(data_mat)
    295 dr = pd.DataFrame(
    296     embedding,
    297     index=data_names,
    298     columns=[
    299         'UMAP_1',
    300         'UMAP_2'])
    301 if not hasattr(scplus_obj, 'dr_cell'):

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py:2772, in UMAP.fit_transform(self, X, y)
   2742 def fit_transform(self, X, y=None):
   2743     """Fit X into an embedded space and return that transformed
   2744     output.
   2745 
   (...)
   2770         Local radii of data points in the embedding (log-transformed).
   2771     """
-> 2772     self.fit(X, y)
   2773     if self.transform_mode == "embedding":
   2774         if self.output_dens:

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py:2516, in UMAP.fit(self, X, y)
   2510     nn_metric = self._input_distance_func
   2511 if self.knn_dists is None:
   2512     (
   2513         self._knn_indices,
   2514         self._knn_dists,
   2515         self._knn_search_index,
-> 2516     ) = nearest_neighbors(
   2517         X[index],
   2518         self._n_neighbors,
   2519         nn_metric,
   2520         self._metric_kwds,
   2521         self.angular_rp_forest,
   2522         random_state,
   2523         self.low_memory,
   2524         use_pynndescent=True,
   2525         n_jobs=self.n_jobs,
   2526         verbose=self.verbose,
   2527     )
   2528 else:
   2529     self._knn_indices = self.knn_indices

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py:328, in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, low_memory, use_pynndescent, n_jobs, verbose)
    325     n_trees = min(64, 5 + int(round((X.shape[0]) ** 0.5 / 20.0)))
    326     n_iters = max(5, int(round(np.log2(X.shape[0]))))
--> 328     knn_search_index = NNDescent(
    329         X,
    330         n_neighbors=n_neighbors,
    331         metric=metric,
    332         metric_kwds=metric_kwds,
    333         random_state=random_state,
    334         n_trees=n_trees,
    335         n_iters=n_iters,
    336         max_candidates=60,
    337         low_memory=low_memory,
    338         n_jobs=n_jobs,
    339         verbose=verbose,
    340         compressed=False,
    341     )
    342     knn_indices, knn_dists = knn_search_index.neighbor_graph
    344 if verbose:

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py:921, in NNDescent.__init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_degree_multiplier, diversify_prob, n_search_trees, tree_init, init_graph, init_dist, random_state, low_memory, max_candidates, n_iters, delta, n_jobs, compressed, parallel_batch_queries, verbose)
    918     if verbose:
    919         print(ts(), "NN descent for", str(n_iters), "iterations")
--> 921     self._neighbor_graph = nn_descent(
    922         self._raw_data,
    923         self.n_neighbors,
    924         self.rng_state,
    925         effective_max_candidates,
    926         self._distance_func,
    927         self.n_iters,
    928         self.delta,
    929         low_memory=self.low_memory,
    930         rp_tree_init=True,
    931         init_graph=_init_graph,
    932         leaf_array=leaf_array,
    933         verbose=verbose,
    934     )
    936 if np.any(self._neighbor_graph[0] < 0):
    937     warn(
    938         "Failed to correctly find n_neighbors for some samples."
    939         " Results may be less than ideal. Try re-running with"
    940         " different parameters."
    941     )

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File ~/.conda/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'print': Cannot determine Numba type of <class 'function'>

File "../../../.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 252:
def nn_descent_internal_low_memory_parallel(
    <source elided>
        if verbose:
            print("\t", n + 1, " / ", n_iters)
            ^

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7f5fc237eb80>))
During: typing of call at /home/jupyter-ayang/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7f5fc237eb80>))
During: typing of call at /home/jupyter-ayang/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)


File "../../../.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 358:
def nn_descent(
    <source elided>
    if low_memory:
        nn_descent_internal_low_memory_parallel(
        ^
```

**Version **
 - Python: 3.8.17
 - SCENIC+: 1.0.1.dev3+g3741a4b.d20230808
 - numba: 0.57.1

**Comment by FynnKr** [comment]
This is probably a compatibility issue between your python and numba version. Other people have this issue e.g. with scanpy; check out:

https://github.com/scverse/scanpy/issues/1652

**Comment by SeppeDeWinter** [comment]
https://github.com/aertslab/scenicplus/issues/256

Yes, it's related to the numba version indeed. Try downgrading to 0.55.

All the best,

Seppe

**Comment by daccachejoe** [comment]
HI Seppe,

Thanks for this solution but unfortunately it did not work for me. Dropping to 0.55 had preflight errors in run_scenic_plus and upgrading to 0.58.1 resulted in the same error. any ideas?

**Comment by daccachejoe** [comment]
Hi - I wanted to provide the error log in case it helps at all but the version switching did not eliminate the error

```
2023-11-22 15:14:30,254 SCENIC+_wrapper INFO     Making eGRNs AUC UMAP

==> scripts/outs/scenicplus-26928430.e <==
Traceback (most recent call last):
  File "scripts/scenicplus-script.py", line 66, in <module>
    raise(e)
  File "scripts/scenicplus-script.py", line 46, in <module>
    run_scenicplus(
  File "/gpfs/data/naiklab/.conda/envs/scenicplus/src/scenicplus/wrappers/run_scenicplus.py", line 290, in run_scenicplus
    run_eRegulons_umap(scplus_obj,
  File "/gpfs/data/naiklab/.conda/envs/scenicplus/src/scenicplus/dimensionality_reduction.py", line 294, in run_eRegulons_umap
    embedding = reducer.fit_transform(data_mat)
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 2887, in fit_transform
    self.fit(X, y, force_all_finite)
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 2608, in fit
    ) = nearest_neighbors(
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py", line 329, in nearest_neighbors
    knn_search_index = NNDescent(
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 921, in __init__
    self._neighbor_graph = nn_descent(
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'print': Cannot determine Numba type of <class 'function'>

File "../../../../../../home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 252:
def nn_descent_internal_low_memory_parallel(
    <source elided>
        if verbose:
            print("\t", n + 1, " / ", n_iters)
            ^

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7fd9d1f13a60>))
During: typing of call at /gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)

During: resolving callee type: type(CPUDispatcher(<function nn_descent_internal_low_memory_parallel at 0x7fd9d1f13a60>))
During: typing of call at /gpfs/home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py (358)


File "../../../../../../home/jd5457/naiklink/jd5457/.conda/envs/scenicplus/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 358:
def nn_descent(
    <source elided>
    if low_memory:
        nn_descent_internal_low_memory_parallel(

```

**Comment by YingxinLin** [comment]
I am having exactly the same error with numba 0.58.1, umap 0.5.4 and scenicplus 1.0.1.dev4+ge4bdd9f under Python 3.8.18.

**Comment by BM-Boris** [comment]
Running run_scenicplus after restarting the kernel with the saved scenic object helped me to avoid this error.

**Comment by yiyelinfeng** [comment]
delete the row:
if verbose:
            print("\t", n + 1, " / ", n_iters)
in pynndescent_.py with function nn_descent_internal_low_memory_parallel and nn_descent_internal_high_memory_parallel can avoid this error.
On the other, this error only occur when cells above 5000.

**Comment by laki-spk** [comment]
Hi @SeppeDeWinter 

Thank you for this awesome tool. I am also getting the same error. I am running it with mouse species. 
>>> umap.__version__
'0.5.5'
>>> numba.__version__
'0.58.1'

Please help. 

Thank you
