### ISSUE TITLE
menr.pkl: _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by alexlenail** [aertslab/scenicplus#244]
Today I re-ran `run_pycistarget` to re-generate menr.pkl. Right after the function finishes successfully, I try opening `menr.pkl` but get this error message: 

```
>>> with open('menr.pkl', 'rb') as f: menr = dill.load(f)
...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
_pickle.UnpicklingError: pickle data was truncated
```

**Version (please complete the following information):**
 - Python: Python 3.9.16 | packaged by conda-forge
 - SCENIC+:  0.1.dev464+g61c17c8.d20230214
- pycistarget: '1.0.2.dev11+g7daf370'

**Comment by alexlenail** [comment]
sorry node just ran out of space
