### ISSUE TITLE
Problem with the exported_pseudobulk function

### ISSUE THREAD

**Issue by flaviagann** [aertslab/scenicplus#262]
Hello!
I'm having some troubles to run the "exported_pseudobulk". I am not able to understand this problem.
obs: In the variable "cell type" I have 10 louvain clusters. 

```
from pycisTopic.pseudobulk_peak_calling import export_pseudobulk
bw_paths, bed_paths = export_pseudobulk(input_data = cell_data,
                 variable = 'cell type',                                                                     
                 sample_id_col = 'sample_id',
                 chromsizes = chromsizes,
                 bed_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/'),  
                 bigwig_path = os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bw_files/'),
                 path_to_fragments = fragments_dict,                                                       
                 n_cpu = 8,                                                                                 
                 normalize_bigwig = True,
                 remove_duplicates = True,
                 _temp_dir = os.path.join(tmp_dir, 'ray_spill'),
                 split_pattern = '-')

```
return. This function is not created a pseudobulk for all my clusters in the cell type column.

```
2023-11-21 07:46:17,181	INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8266 

(export_pseudobulk_ray pid=483651) 2023-11-21 07:46:19,684 cisTopic     INFO     Creating pseudobulk for H4_ADP
(export_pseudobulk_ray pid=483655) 2023-11-21 07:46:19,672 cisTopic     INFO     Creating pseudobulk for SWAT
(export_pseudobulk_ray pid=483653) 2023-11-21 07:46:19,774 cisTopic     INFO     Creating pseudobulk for H6_ASPC [repeated 7x across cluster]
```
After that, I performed the next step:

```
import pickle
bed_paths = pickle.load(open(os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/bed_paths.pkl'), 'rb'))
bw_paths =  pickle.load(open(os.path.join(work_dir, 'scATAC/consensus_peak_calling/pseudobulk_bed_files/bw_paths.pkl'), 'rb'))
from pycisTopic.pseudobulk_peak_calling import peak_calling
macs_path='macs2'
# Run peak calling
narrow_peaks_dict = peak_calling(macs_path,
                                 bed_paths,
                                 os.path.join(work_dir, 'scATAC/consensus_peak_calling/MACS/'),
                                 genome_size='hs',
                                 n_cpu=8,
                                 input_format='BEDPE',
                                 shift=73,
                                 ext_size=146,
                                 keep_dup = 'all',
                                 q_value = 0.05,
                                 _temp_dir = os.path.join(tmp_dir, 'ray_spill'))

```

and return this error:
```
2023-11-21 07:47:00,579	INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8266 

(macs_call_peak_ray pid=484398) 2023-11-21 07:47:02,956 cisTopic     INFO     Calling peaks for H6_ASPC with macs2 callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz --name H6_ASPC  --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda

---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
Cell In[94], line 7
      5 macs_path='macs2'
      6 # Run peak calling
----> 7 narrow_peaks_dict = peak_calling(macs_path,
      8                                  bed_paths,
      9                                  os.path.join(work_dir, 'scATAC/consensus_peak_calling/MACS/'),
     10                                  genome_size='hs',
     11                                  n_cpu=8,
     12                                  input_format='BEDPE',
     13                                  shift=73,
     14                                  ext_size=146,
     15                                  keep_dup = 'all',
     16                                  q_value = 0.05,
     17                                  _temp_dir = os.path.join(tmp_dir, 'ray_spill'))

File ~/anaconda3/envs/cell2/lib/python3.9/site-packages/pycisTopic/pseudobulk_peak_calling.py:415, in peak_calling(macs_path, bed_paths, outdir, genome_size, n_cpu, input_format, shift, ext_size, keep_dup, q_value, nolambda, **kwargs)
    413 if n_cpu > 1:
    414     ray.init(num_cpus=n_cpu, **kwargs)
--> 415     narrow_peaks = ray.get(
    416         [
    417             macs_call_peak_ray.remote(
    418                 macs_path,
    419                 bed_paths[name],
    420                 name,
    421                 outdir,
    422                 genome_size,
    423                 input_format,
    424                 shift,
    425                 ext_size,
    426                 keep_dup,
    427                 q_value,
    428                 nolambda,
    429             )
    430             for name in list(bed_paths.keys())
    431         ]
    432     )
    433     ray.shutdown()
    434 else:

File ~/anaconda3/envs/cell2/lib/python3.9/site-packages/ray/_private/auto_init_hook.py:24, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     21 @wraps(fn)
     22 def auto_init_wrapper(*args, **kwargs):
     23     auto_init_ray()
---> 24     return fn(*args, **kwargs)

File ~/anaconda3/envs/cell2/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/anaconda3/envs/cell2/lib/python3.9/site-packages/ray/_private/worker.py:2563, in get(object_refs, timeout)
   2561     worker.core_worker.dump_object_store_memory_usage()
   2562 if isinstance(value, RayTaskError):
-> 2563     raise value.as_instanceof_cause()
   2564 else:
   2565     raise value

RayTaskError(RuntimeError): ray::macs_call_peak_ray() (pid=484398, ip=143.106.218.173)
  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'macs2 callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz --name H6_ASPC  --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

ray::macs_call_peak_ray() (pid=484398, ip=143.106.218.173)
  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/site-packages/pycisTopic/pseudobulk_peak_calling.py", line 585, in macs_call_peak_ray
    MACS_peak_calling = MACSCallPeak(
  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/site-packages/pycisTopic/pseudobulk_peak_calling.py", line 658, in __init__
    self.call_peak()
  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/site-packages/pycisTopic/pseudobulk_peak_calling.py", line 699, in call_peak
    raise RuntimeError(
RuntimeError: command 'macs2 callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz --name H6_ASPC  --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda' return with error (code 1): b'INFO  @ Tue, 21 Nov 2023 07:47:03: \n# Command line: callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz --name H6_ASPC --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda\n# ARGUMENTS LIST:\n# name = H6_ASPC\n# format = BEDPE\n# ChIP-seq file = [\'scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz\']\n# control file = None\n# effective genome size = 2.70e+09\n# band width = 300\n# model fold = [5, 50]\n# qvalue cutoff = 5.00e-02\n# The maximum gap between significant sites is assigned as the read length/tag size.\n# The minimum length of peaks is assigned as the predicted fragment length "d".\n# Larger dataset will be scaled towards smaller dataset.\n# Range for calculating regional lambda is: 10000 bps\n# Broad region calling is off\n# Paired-End mode is on\n# Searching for subpeak summits is on\n \nINFO  @ Tue, 21 Nov 2023 07:47:03: #1 read fragment files... \nINFO  @ Tue, 21 Nov 2023 07:47:03: #1 read treatment fragments... \nTraceback (most recent call last):\n  File "/home/razor/anaconda3/envs/cell2/bin/macs2", line 653, in <module>\n    main()\n  File "/home/razor/anaconda3/envs/cell2/bin/macs2", line 51, in main\n    run( args )\n  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/site-packages/MACS2/callpeak_cmd.py", line 64, in run\n    if options.PE_MODE: (treat, control) = load_frag_files_options (options)\n  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/site-packages/MACS2/callpeak_cmd.py", line 349, in load_frag_files_options\n    tp = options.parser(options.tfile[0], buffer_size=options.buffer_size)\n  File "MACS2/IO/Parser.pyx", line 330, in MACS2.IO.Parser.GenericParser.__init__\n  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/gzip.py", line 58, in open\n    binary_file = GzipFile(filename, gz_mode, compresslevel)\n  File "/home/razor/anaconda3/envs/cell2/lib/python3.9/gzip.py", line 173, in __init__\n    fileobj = self.myfileobj = builtins.open(filename, mode or \'rb\')\nFileNotFoundError: [Errno 2] No such file or directory: \'scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H6_ASPC.bed.gz\'\n'

(macs_call_peak_ray pid=484394) 2023-11-21 07:47:03,007 cisTopic     INFO     Calling peaks for H7_ASPC with macs2 callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/H7_ASPC.bed.gz --name H7_ASPC  --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda
(macs_call_peak_ray pid=484395) 2023-11-21 07:47:03,084 cisTopic     INFO     Calling peaks for SWAT with macs2 callpeak --treatment scenic/scATAC/consensus_peak_calling/pseudobulk_bed_files/SWAT.bed.gz --name SWAT  --outdir scenic/scATAC/consensus_peak_calling/MACS/ --format BEDPE --gsize hs --qvalue 0.05 --nomodel --shift 73 --extsize 146 --keep-dup all --call-summits --nolambda
```

At first I thought the problem was with my scRNAseq data or with the scATACseq fragment data, but I did the same analysis with the data from the pmbc tutorial available and exactly the same thing happens. Basically the pseudobulk function does not calculate for all Cell type variables.
I'm new to this type of analysis and if you can help me, I'd be grateful.

**Comment by SeppeDeWinter** [comment]
Hi @flaviagann 

Can you check wether all the chromosome names in you fragments file are also present in your chromsizes file?

All the best,

Seppe

**Comment by flaviagann** [comment]
Hey, @SeppeDeWinter !! Thank you for the code!

My output for the first is:
{'scATAC'}
{'H8_ASPC', 'H7_ASPC', 'H3_ADP', 'H4_ADP', 'H1_ADP', 'H6_ASPC', 'H2_ADP', 'H5_ADP', 'SWAT', 'H9_ADP'}
dict_keys(['scATAC'])

Now I understand how the code works and I think realize where the error is.
When I run the final part of the code before building the pseudobulk, the fragments data frame returns as empty.

The scATACseq barcode names do not match the scRNAseq barcode names (they are two different public data from the same tissue), there are differences in the number of characters.
Example:
scATACseq barcodes: CTATCTCTCCTATGCACCGGAT
scRNAseq barcodes: TTTGTTGCAAGGCTTT

Can the code only combine data if the barcode names match? right? Is there another way? 
Sorry for the noob questions, but I'm using CellOracle too and the data matched perfectly.

**Comment by SeppeDeWinter** [comment]
Hi @flaviagann 

So the data you are using is not multiome (i.e. it's seperate scRNA-seq and scATAC-seq)?

The barcode names are used to group cells based on the cell type annotation, and then generate pseudobulks based on that grouping.

If the barcodes don't match between the scATAC-seq data ( fragment file ) and the cell type annotation (celldata) this is not possible to do.

All the best,

Seppe
