### ISSUE TITLE
After running GSEA. I got stuck on getting the regulons.

### ISSUE THREAD

**Issue by rogercasalsfr** [aertslab/scenicplus#288]
**Describe the bug**
Hi everyone, 
I am currently running SCENIC+ on an HPC machine without internet access. I encountered an issue during GSEA calculations, which I believe could be resolved with additional RAM. Once I address this, I plan to proceed to the next step, building the gene regulatory network (GRN). 
I have attempted two different approaches to construct the GRN, encountering distinct issues with each. I suspect these issues may be related to either the data or the programs. I am reaching out to inquire whether anyone has encountered similar challenges and if they might be able to provide insights into potential solutions.
Your assistance would be greatly appreciated. Thank you.

**To Reproduce**
I use the same code lines as the SCENIC+ tutorials

**Error output**
I have this error when I use run_scenicplus
```
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'GEX_celltype'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "model.py", line 29, in <module>
    run_scenicplus(
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/scenicplus/wrappers/run_scenicplus.py", line 253, in run_scenicplus
    generate_pseudobulks(scplus_obj,
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/scenicplus/cistromes.py", line 215, in generate_pseudobulks
    categories = list(set(cell_data.loc[:, variable]))
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1068, in __getitem__
    return self._getitem_tuple(key)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1248, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 968, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1313, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexing.py", line 1261, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/generic.py", line 4042, in xs
    return self[key]
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/apps/PYTHON/environments/scenicplus_env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'GEX_celltype'
```

And this error if I try to use from scenicplus.grn_builder.gsea_approach import build_grn
```
Traceback (most recent call last):
  File "inferandgrn.py", line 63, in <module>
    pickle.dump(scplus_obj, f)
_pickle.PicklingError: Can't pickle <class 'pandas.core.frame.r2g'>: attribute lookup r2g on pandas.core.frame failed
```

**Expected behavior**
It should get the scenicplus object result without any problem

**Screenshots**

**Version (please complete the following information):**
Scenicplus version --> 1.0.1.dev4+ge4bdd9f
Python version --> Python 3.8.8

**Additional context**

**Comment by SeppeDeWinter** [comment]
Hi @rogercasalsfr 

For the error related to `KeyError: 'GEX_celltype'`, what command were you running? I Would suspect that you don't have this field (`GEX_celltype`) in your cell metadata.

Related to the other error you are facing, and also the high amount of memory requirements you are mentioning. I would suggest to use the development branch of the code. This code is a lot more efficient. See: https://github.com/aertslab/scenicplus/discussions/202 for more information.

I hope this helps?

All the best.

Seppe

**Comment by SeppeDeWinter** [comment]
Hi @rogercasalsfr 

For your first error, please see: https://github.com/aertslab/scenicplus/issues/203. I was still not able to replicate this issue (it has something to do with numa and UMAP incompatibilities). Again, this issue is resolved in the development branch of the code so I would highly recommend to use that code. That code will also become the default code very soon!

There are now also tutorials on how to use this branch: https://scenicplus.readthedocs.io/en/development/.

related to your second question, what version of SCENIC+ are you using to run this code?

```python

import scenicplus
scenicplus.__version__

```

All the best,

Seppe
