### ISSUE TITLE
error runing scenic+

### ISSUE THREAD

**Issue by ACAIDI** [aertslab/scenicplus#438]
Hi,
Thank you for developing this tool. I tried to run Scenic+ on my mutiome data and I got an error message that I don't quite understand.
Could you help me with this issue.
Thanks in advance
This is the error message :+1: 
Traceback (most recent call last):
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/bin/scenicplus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 1137, in main
    args.func(args)
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 388, in motif_enrichment_cistarget
    run_motif_enrichment_cistarget(
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/scenicplus/cli/commands.py", line 242, in run_motif_enrichment_cistarget
    cistarget_results: List[cisTarget] = joblib.Parallel(
                                         ^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/userdata/conda/envs/scenicplus/lib/python3.11/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
[Tue Jul 23 15:45:06 2024]
Error in rule motif_enrichment_cistarget:
    jobid: 12
    output: ctx_results.hdf5, ctx_results.html
    shell:
        
            scenicplus grn_inference motif_enrichment_cistarget                 --region_set_folder /mnt/beegfs/scratch/multiome/integrated_objects/scenicplus_analysis/region_sets                 --cistarget_db_fname /mnt/beegfs/userdata/databases/motif_collections/hg38_screen_v10_clust.regions_vs_motifs.rankings.feather                 --output_fname_cistarget_result ctx_results.hdf5                 --temp_dir /mnt/beegfs/scratch/multiome/integrated_objects/scenicplus_analysis/tmp                 --species homo_sapiens                 --fr_overlap_w_ctx_db 0.4                 --auc_threshold 0.005                 --nes_threshold 3.0                 --rank_threshold 0.05                 --path_to_motif_annotations /mnt/beegfs/userdata/databases/motif_collections/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl                 --annotation_version v10nr_clust                 --motif_similarity_fdr 0.001                 --orthologous_identity_threshold 0.0                 --annotations_to_use Direct_annot Orthology_annot                 --write_html                 --output_fname_cistarget_html ctx_results.html                 --n_cpu 32
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/beegfs/scratch/multiome/integrated_objects/scenicplus_analysis/scplus_pipeline/Snakemake/.snakemake/log/2024-07-23T154118.004923.snakemake.log
slurmstepd: error: Detected 9 oom-kill event(s) in StepId=5783995.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by SeppeDeWinter** [comment]
Hi @ACAIDI 

Could it be that you are running out of memory?


All the best,

Seppe
