### ISSUE TITLE
Error in running grn_inference region_to_gene

### ISSUE THREAD

**Issue by Longity** [aertslab/scenicplus#481]
**Describe the bug**
"Hi, I am trying to use region_to_gene in the Snakemake pipeline, but I encountered an error: 'ValueError: Input y contains NaN.'"

**To Reproduce**

```bash
scenicplus grn_inference region_to_gene
             --multiome_mudata_fname /home/may/vscode/scv/pscturoial/outs_scenic/ACC_GEX.h5mu
             --search_space_fname /home/may/vscode/scv/pscturoial/outs_scenic/search_space.tsv
             --temp_dir /home/may/vscode/scv/pscturoial/tmp
             --out_region_to_gene_adjacencies /home/may/vscode/scv/pscturoial/outs_scenic/region_to_gene_adj.tsv
             --importance_scoring_method GBM
             --correlation_scoring_method SR
             --n_cpu 8

```

**Error output**

```python
2024-10-15 15:36:47,975 SCENIC+      INFO     Reading multiome MuData.
/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/anndata/_core/anndata.py:522: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(
/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/anndata/_core/anndata.py:522: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
  warnings.warn(
2024-10-15 15:36:49,617 SCENIC+      INFO     Reading search space
2024-10-15 15:36:49,701 R2G          INFO     Calculating region to gene importances, using GBM method
Running using 1 cores:   0%|                           | 0/3806 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/may/miniconda3/envs/scep3118/bin/scenicplus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 1137, in main
    args.func(args)
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/cli/scenicplus.py", line 330, in TF_to_gene
    infer_region_to_gene(
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/cli/commands.py", line 739, in infer_region_to_gene
    adj = calculate_regions_to_genes_relationships(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/enhancer_to_gene.py", line 261, in calculate_regions_to_genes_relationships
    region_to_gene_importances = _score_regions_to_genes(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/enhancer_to_gene.py", line 219, in _score_regions_to_genes
    joblib.Parallel(
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/scenicplus/enhancer_to_gene.py", line 143, in _score_regions_to_single_gene
    fitted_model = arboreto_core.fit_model(regressor_type=regressor_type,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/arboreto/core.py", line 143, in fit_model
    return do_sklearn_regression()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/arboreto/core.py", line 138, in do_sklearn_regression
    regressor.fit(tf_matrix, target_gene_expression)
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/ensemble/_gb.py", line 416, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/base.py", line 622, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1162, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1172, in _check_y
    y = check_array(
        ^^^^^^^^^^^^
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/utils/validation.py", line 957, in check_array
    _assert_all_finite(
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/may/miniconda3/envs/scep3118/lib/python3.11/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input y contains NaN.
```

**Version (please complete the following information):**
 - Python: 3.11.8
 - SCENIC+: 1.0a1

Additional context
The data is example data from tutorial 10x: Flash-Frozen Human Healthy Brain Tissue (3k)

**Comment by SeppeDeWinter** [comment]
Hi @Longity 

Can you load your mudata object (`/home/may/vscode/scv/pscturoial/outs_scenic/ACC_GEX.h5mu`) and check wether either the gene expression matrix or accessibility matrix contains NaNs?

```python

import mudata

mdata = mudata.read("/home/may/vscode/scv/pscturoial/outs_scenic/ACC_GEX.h5mu")

df_exp_mtx = mdata["scRNA"].to_df() # <-- check this dataframe
df_acc_mtx = mdata["scATAC"].to_df()# <-- check this dataframe

```

All the best,

Seppe

**Comment by dcolinmorgan** [comment]
i am seeing NaNs for 10 topics as [1966 rows x 5499 columns]. 

ended up appending `.fillna(0)` to `.to_df()` throughout `cli.commands.py`
