### ISSUE TITLE
کتابخانه scenicplus نصب نمیشه یک ماهه تلاش میکنم حتی در محیط مجازی کوندا نیز نصب نمیشه ارور زیر رو میده لطفا کری کنید بشه کتابخانه رو نصب کرد

### ISSUE THREAD

**Issue by sajadfatahi** [aertslab/scenicplus#507]
Sure! Here’s the translation of your request into English:

---

The **scenicplus** library is not installing. I've been trying for a month, and it doesn't install even in a Conda virtual environment. It gives the following error. Please help me to install the library.

--- 

If you provide the specific error message you're encountering, I can assist you further in troubleshooting the installation of the **scenicplus** library.

Collecting pybigtools==0.1.2 (from scenicplus==1.0a1)
  Using cached pybigtools-0.1.2-cp311-none-win_amd64.whl.metadata (1.3 kB)
Collecting pybigwig==0.3.22 (from scenicplus==1.0a1)
  Using cached pyBigWig-0.3.22.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\vira\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\vira\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vira\anaconda3\envs\scenicplus\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vira\AppData\Local\Temp\pip-build-env-4cmxzasa\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vira\AppData\Local\Temp\pip-build-env-4cmxzasa\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\vira\AppData\Local\Temp\pip-build-env-4cmxzasa\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SeppeDeWinter** [comment]
Hi @sajadfatahi 

Can you please detail the steps you took to install SCENIC+

All the best,

Seppe

**Comment by ghuls** [comment]
Use a Linux machine to install scenicplus. pyBigWig (https://pypi.org/project/pyBigWig/#files) does not have Windows wheels available and is unlikely to build on Windows.
